image: ubuntu:focal

stages:
  # - test
  # - build
  - package
  - publish

test:unittests:
   stage: test
   before_script:
     - apt update
     - apt -y install build-essential python3-dev librsync-dev lsb-release python3-apsw python3-crypto python3-magic python3-mysqldb python3-openssl python3-pampy python3-pip python3-sqlalchemy cpio iproute2
     - pip install .[test,qa]
   script:
     - ./run_qa.sh
   artifacts:
     name: 'python-opsi_QA'
     paths:
       - pylint.txt
       - pep8.txt
       - coverage.xml
     reports:
       junit: testreport.xml
     expire_in: 1 day


#build:documentation:
#  stage: build
#  script:
#    - apt update
#    - apt -y install build-essential default-libmysqlclient-dev libssl-dev python3-apsw python3-pip
#    - pip3 install .
#    - pip3 install sphinx
#    - sphinx-apidoc --force --separate -o doc/src OPSI/
#    - sphinx-build -b html -d doc/_build/doctrees -D latex_paper_size=a4 -D latex_paper_size=letter doc/src/ doc/python-opsi/
#  after_script:
#    - mv doc/python-opsi/ .
#  artifacts:
#    name: 'python-opsi_documentation'
#    paths:
#      - python-opsi/
#    expire_in: 1 day


package:obs:
  stage: package
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update
    - apt -y install python3-all python3-pip dh-python python3-venv curl libmysqlclient-dev debhelper osc
    #- curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
    #- source $HOME/.poetry/env
    - pip3 install poetry
    - poetry install
    - poetry run opsi-dev-tool -l debug --obs-update-package https://obs.uib.local home:uibmz:opsi:4.2:experimental
  #only:
  #    - /^release/.*$/i
  #    - tags
  #    - web

publish:uibpypi:
  stage: publish
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update
    - apt -y upgrade
    - apt -y install python3-all python3-pip dh-python python3-venv libmysqlclient-dev curl
    #- curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
    #- source $HOME/.poetry/env
    - pip3 install poetry
    - poetry install
    - poetry run opsi-dev-tool -l info --uib-pypi-publish
