image: python:3.7-stretch

stages:
  # - test
  - build
  - package
  - publish

#test:unittests:
#   stage: test
#   before_script:
#     - apt update
#     - apt -y install build-essential python3-dev librsync-dev lsb-release python3-apsw python3-crypto python3-magic python3-mysqldb python3-openssl python3-pampy python3-pip python3-sqlalchemy
#     - pip install .[test,qa]
#   script:
#     - ./run_qa.sh
#   artifacts:
#     name: 'python-opsi_QA'
#     paths:
#       - pylint.txt
#       - pep8.txt
#       - coverage.xml
#     reports:
#       junit: testreport.xml
#     expire_in: 1 day


build:documentation:
  stage: build
  script:
    - apt update
    - apt -y install build-essential default-libmysqlclient-dev libssl-dev python3-apsw python3-pip
    - pip3 install .
    - pip3 install sphinx
    - sphinx-apidoc --force --separate -o doc/src OPSI/
    - sphinx-build -b html -d doc/_build/doctrees -D latex_paper_size=a4 -D latex_paper_size=letter doc/src/ doc/python-opsi/
  after_script:
    - mv doc/python-opsi/ .
  artifacts:
    name: 'python-opsi_documentation'
    paths:
      - python-opsi/
    expire_in: 1 day


package:obs:
  stage: package
  script:
    - apt update
    - apt -y install debhelper osc
    - pip3 install --trusted-host pypi.uib.gmbh --index-url http://pypi.uib.gmbh:8080/simple opsi-dev-tools
    - python3 -m opsidevtools -l info --obs-update-package https://obs.uib.local home:uibmz:opsi:4.2:experimental
  #only:
  #    - /^release/.*$/i
  #    - tags
  #    - web

publish:uibpypi:
  stage: publish
  script:
    - apt update
    - apt -y install debhelper osc
    - pip3 install --trusted-host pypi.uib.gmbh --index-url http://pypi.uib.gmbh:8080/simple opsi-dev-tools
    - python3 -m opsidevtools -l info --uib-pypi-publish
