image: ubuntu:18.04

stages:
  - test
  - package


run unittests:
  image: docker.uib.gmbh/py-test-image
  stage: test
  before_script:
#    - hostname test.uib.local
#    - apt update
#    - apt -y install build-essential python-dev librsync-dev lsb-release python-apsw python-crypto python-ldaptor python-m2crypto python-magic python-mysqldb python-newt python-openssl python-pam python-pip python-sqlalchemy python-twisted-web
    - apt -y install cpio iproute2
    - pip install -r requirements-qa.txt
#    - pip install https://launchpad.net/duplicity/0.6-series/0.6.24/+download/duplicity-0.6.24.tar.gz
  script:
    - ./run_qa.sh
  artifacts:
    name: 'python-opsi_QA'
    paths:
      - pylint.txt
      - pep8.txt
      - coverage.xml
    reports:
      junit: testreport.xml
    expire_in: 1 day


build documentation:
  stage: package
  before_script:
    - apt update
    - apt -y install python3-pip
    - pip3 install .
    - pip3 install sphinx
  script:
    - sphinx-apidoc --force --separate -o doc/src OPSI/
    - sphinx-build -b html -d doc/_build/doctrees -D latex_paper_size=a4 -D latex_paper_size=letter doc/src/ doc/python-opsi/
  after_script:
    - mv doc/python-opsi/ .
  artifacts:
    name: 'python-opsi_documentation'
    paths:
      - python-opsi/
    expire_in: 1 day


package for OBS:
  stage: package
  before_script:
    - apt update
    - apt install -y devscripts debhelper dh-python gettext lsb-release python3-all python3-setuptools
  script:
    - ./create_source.sh
    - test -f python3-opsi_*.dsc
    - test -f python3-opsi_*.tar.gz
    - test -f python3-opsi.spec
  artifacts:
    name: 'python-opsi_OBS'
    paths:
      - python3-opsi_*.dsc
      - python3-opsi_*.tar.gz
      - python3-opsi.spec
    expire_in: 2 days
  only:
      - /^release/.*$/i
      - tags
      - web
