image: ubuntu:focal

stages:
  - test
  # - build
  - package
  - publish

test:pytests:
  image: ubuntu:focal
  services:
    - mysql:5.7
  variables:
    MYSQL_ROOT_PASSWORD: "opsi"
    MYSQL_DATABASE: "opsi"
    MYSQL_USER: "opsi"
  stage: test
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update
    - apt -y install python3-all python3-pip dh-python python3-venv curl libmysqlclient-dev mysql-client git
    - pip3 install poetry
    - cp tests/Backends/config.py.gitlabci tests/Backends/config.py
    # cloning opsi-server for data directory
    - git clone -b master https://gitlab.uib.gmbh/uib/opsi-server.git ../opsi-server
    - ln -s ../opsi-server/opsi-server_data/etc data
    - mkdir -p /etc/opsi
    - echo ${OPSI_TEST_MODULES} > /etc/opsi/modules
    - poetry install
    # Todo: crazy bug
    - poetry remove pycryptodome
    - poetry add pycryptodome
    # Deactivate mysql strict mode
    - mysql --host=mysql --user=root --password=${MYSQL_ROOT_PASSWORD} -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION';"
  script:
    - echo waiting 20sec to wait for mysql
#    - sleep 20
    - poetry run ./run_qa.sh
  artifacts:
    name: 'python-opsi_QA'
    paths:
        - pylint.txt
        - pep8.txt
        - coverage.xml
    reports:
        junit: testreport.xml
    expire_in: 1 day


#build:documentation:
#  stage: build
#  script:
#    - apt update
#    - apt -y install build-essential default-libmysqlclient-dev libssl-dev python3-apsw python3-pip
#    - pip3 install .
#    - pip3 install sphinx
#    - sphinx-apidoc --force --separate -o doc/src OPSI/
#    - sphinx-build -b html -d doc/_build/doctrees -D latex_paper_size=a4 -D latex_paper_size=letter doc/src/ doc/python-opsi/
#  after_script:
#    - mv doc/python-opsi/ .
#  artifacts:
#    name: 'python-opsi_documentation'
#    paths:
#      - python-opsi/
#    expire_in: 1 day


package:obs:
  stage: package
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update
    - apt -y install python3-all python3-pip dh-python python3-venv curl libmysqlclient-dev debhelper osc
    #- curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
    #- source $HOME/.poetry/env
    - pip3 install poetry
    - poetry install
    - poetry run opsi-dev-tool -l debug --obs-update-package https://obs.uib.local home:uibmz:opsi:4.2:experimental
  #only:
  #    - /^release/.*$/i
  #    - tags
  #    - web

publish:uibpypi:
  stage: publish
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update
    - apt -y upgrade
    - apt -y install python3-all python3-pip dh-python python3-venv libmysqlclient-dev curl
    #- curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
    #- source $HOME/.poetry/env
    - pip3 install poetry
    - poetry install
    - poetry run opsi-dev-tool -l info --uib-pypi-publish
