image: ubuntu:latest

stages:
  - build
  - package


build documentation:
  stage: build
  before_script:
    - apt update
    - apt install python-pip
    - pip install 'sphinx<1.5'
  script:
    - sphinx-apidoc --force --separate -o doc/src OPSI/
    - sphinx-build -b html -d doc/_build/doctrees -D latex_paper_size=a4 -D latex_paper_size=letter doc/src/ doc/python-opsi/
  after_script:
    - cd doc
    - tar -czvf python-opsi-documentation.tar.gz python-opsi/
  artifacts:
    paths:
      - doc/python-opsi-documentation.tar.gz
    expire_in: 1 day


package for OBS:
  stage: package
  before_script:
    - apt update
    - apt install -y devscripts debhelper dh-python gettext lsb-release python-all python-setuptools
  script:
    - ./create_source.sh
    - test -f python-opsi_*.dsc
    - test -f python-opsi_*.tar.gz
    - test -f python-opsi.spec
  artifacts:
    paths:
      - python-opsi_*.dsc
      - python-opsi_*.tar.gz
      - python-opsi.spec
    expire_in: 2 days
  only:
      - /^release/.*$/i
      - tags
      - web
