[tool.poetry]
name = "python-opsi"
version = "4.2.0.16"
description = "The opsi python library"
authors = ["Jan Schneider <j.schneider@uib.de>"]
license = "AGPL-3.0"
packages = [
    { include = "OPSI" }
]
include = [
    "data/**/*.conf",
    "data/**/*.conf.example",
    "data/hwaudit/locales/*"
]

[tool.poetry.dependencies]
python = "^3.6"
python-pam = "^1.8.4"
SQLAlchemy = "^1.3.15"
pyasn1 = "^0.4.8"
pyCrypto = "^2.6.1"
pyOpenSSL = "^19.1.0"
twisted = {extras = ["tls"], version = "^20.3.0"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
