[tool.poetry]
name = "python-opsi"
version = "4.2.0.181"
description = "The opsi python library"
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
maintainers = ["uib GmbH <info@uib.de>"]
authors = ["uib GmbH <info@uib.de>"]
packages = [
    { include = "OPSI" },
    { include = "opsicommon" }
]
include = [
    "python-opsi_data/**/*"
]

[[tool.poetry.source]]
name = "uibpypi"
url = "http://pypi.uib.gmbh:8080/simple"

[tool.poetry.dependencies]
python = "^3.7"
python-pam = "^1.8.4"
sqlalchemy = "~1.3"
pyasn1 = "^0.4.8"
pyOpenSSL = "^20.0.1"
twisted = {extras = ["tls"], version = "^21.2.0"}
ldap3 = "^2.9"
pycryptodome = "^3.10.1"
psutil = "^5.8.0"
pywin32 = {platform = "win32", version = "^227"}
wmi = {platform = "win32", version = "^1.5.1"}
distro = {platform = "linux", version = "^1.5.0"}
mysqlclient = {platform = "linux", version = "^2.0.3"}
colorlog = "^4.8.0"
pefile = "^2019.4.18"
ruyaml = "^0.20.0"
lz4 = "^3.1.3"
service-identity = "^18.1.0"
msgpack = "^1.0.2"

[tool.poetry.dev-dependencies]
opsi-dev-tools = "^1.0"
pytest = "^6.2.3"
pytest-cov = "^2.11.1"
pylint = "^2.7.4"
flake8 = "^3.9.0"
mock = "^4.0.3"
pytest-asyncio = "^0.14.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
