[tool.poetry]
name = "python-opsi"
version = "4.2.0.142"
description = "The opsi python library"
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
maintainers = ["uib GmbH <info@uib.de>"]
authors = ["uib GmbH <info@uib.de>"]
packages = [
    { include = "OPSI" },
    { include = "opsicommon" }
]
include = [
    "python-opsi_data/**/*"
]

[[tool.poetry.source]]
name = "uibpypi"
url = "http://pypi.uib.gmbh:8080/simple"

[tool.poetry.dependencies]
python = "^3.7"
python-pam = "^1.8.4"
SQLAlchemy = "^1.3.15"
pyasn1 = "^0.4.8"
pyOpenSSL = "^19.1.0"
twisted = {extras = ["tls"], version = "^20.3.0"}
ldap3 = "^2.8.1"
pycryptodome = "^3.9.7"
psutil = "^5.7.0"
pywin32 = {platform = "win32", version = "^227"}
wmi = {platform = "win32", version = "^1.5.1"}
distro = {platform = "linux", version = "^1.5.0"}
mysqlclient = {platform = "linux", version = "^1.4.6"}
colorlog = "^4.2.1"
pefile = "^2019.4.18"
ruyaml = "^0.19.2"
lz4 = "^3.1.1"
service-identity = "^18.1.0"

[tool.poetry.dev-dependencies]
opsi-dev-tools = "^1.0"
pytest = "^5.4.3"
pytest-cov = "^2.9.0"
pylint = "^2.5.2"
flake8 = "^3.8.2"
mock = "^4.0.2"
pytest-asyncio = "^0.12.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
