[tool.poetry]
name = "python-opsi"
version = "4.2.0.263"
description = "The opsi python library"
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
maintainers = ["uib GmbH <info@uib.de>"]
authors = ["uib GmbH <info@uib.de>"]
packages = [
    { include = "OPSI" }
]
include = [
    "python-opsi_data/**/*"
]

[[tool.poetry.source]]
name = "uibpypi"
url = "https://pypi.uib.gmbh/simple"

[tool.poetry.dependencies]
python = "^3.7"
python-pam = "^1.8.4"
sqlalchemy = "^1.4"
pyasn1 = "^0.4.8"
pyOpenSSL = "^21.0.0"
twisted = {extras = ["tls"], version = "^21.2.0"}
ldap3 = "^2.9"
pycryptodome = "^3.10.1"
psutil = "^5.8.0"
pywin32 = {platform = "win32", version = "^227"}
wmi = {platform = "win32", version = "^1.5.1"}
distro = {platform = "linux", version = "^1.5.0"}
mysqlclient = {platform = "linux", version = "^2.0.3"}
colorlog = "^6.6.0"
pefile = "^2021.9.3"
ruyaml = "^0.91.0"
lz4 = "^3.1.3"
service-identity = "^21.1.0"
msgpack = "^1.0.2"
attrs = "^21.2.0"
pexpect = "^4.8.0"
python-opsi-common = "^4.2.0"

[tool.poetry.dev-dependencies]
opsi-dev-tools = "^1.0"
pytest = "^6.2.3"
pytest-asyncio = "^0.16.0"
pytest-cov = "^3.0.0"
pylint = "^2.7.4"
flake8 = "^4.0.1"
mock = "^4.0.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
