[tool.poetry]
name = "python-opsi"
version = "4.2.0.270"
description = "The opsi python library"
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
maintainers = ["uib GmbH <info@uib.de>"]
authors = ["uib GmbH <info@uib.de>"]
packages = [
    { include = "OPSI" }
]
include = [
    "python-opsi_data/**/*"
]

[[tool.poetry.source]]
name = "uibpypi"
url = "https://pypi.uib.gmbh/simple"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
attrs = "^21.2"
colorlog = "^6.6"
distro = {platform = "linux", version = "^1.5"}
ldap3 = "^2.9"
lz4 = "^3.1"
msgpack = "^1.0"
mysqlclient = {platform = "linux", version = "^2.0"}
pefile = "^2021.9"
pexpect = "^4.8"
psutil = "^5.8"
pyasn1 = "^0.4"
pycryptodome = "^3.10"
pyopenssl = "^22.0"
python-opsi-common = "^4.2.0.272"
python-pam = "^1.8"
pywin32 = {platform = "win32", version = "^303"}
ruyaml = "^0.91"
service-identity = "^21.1"
sqlalchemy = "^1.4"
twisted = {extras = ["tls"], version = "^21.2"}
wmi = {platform = "win32", version = "^1.5"}

[tool.poetry.dev-dependencies]
flake8 = "^4.0"
mock = "^4.0"
opsi-dev-tools = "^1.0"
pylint = "^2.7"
pytest = "^6.2"
pytest-asyncio = "^0.16"
pytest-cov = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
