[tool.poetry]
name = "python-opsi"
version = "4.2.0.25"
description = "The opsi python library"
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
maintainers = ["uib GmbH <info@uib.de>"]
authors = ["uib GmbH <info@uib.de>"]
packages = [
    { include = "OPSI" }
]
include = [
    "python-opsi_data/**/*"
]

[[tool.poetry.source]]
name = "uibpypi"
url = "http://pypi.uib.gmbh:8080/simple"

[tool.poetry.dependencies]
python = "^3.6"
python-pam = "^1.8.4"
SQLAlchemy = "^1.3.15"
pyasn1 = "^0.4.8"
pyOpenSSL = "^19.1.0"
twisted = {extras = ["tls"], version = "^20.3.0"}
python-magic = "^0.4.15"
ldap3 = "^2.7"
PyCryptodome = "^3.9.7"
pywin32 = {platform = "win32", version = "^227"}
wmi = {platform = "win32", version = "^1.5.1"}

[tool.poetry.dev-dependencies]
opsi-dev-tools = "^1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
